insert into public.menu_items (name_en, name_am, description, price, category, image_url, available) values
('Fruit Punch', 'ፍሩት ፑንች', null, 400, 'Salads', 'https://commons.wikimedia.org/wiki/Special:FilePath/Fruit%20bowl%20with%20fruits.png', true),
('Normal Vegetable Salad', 'ኖርማል አትክልት', null, 345, 'Salads', 'https://commons.wikimedia.org/wiki/Special:FilePath/Composed%20salad.jpg', true),
('Special Vegetable Salad', 'ስፔሻል አትክልት', null, 575, 'Salads', 'https://commons.wikimedia.org/wiki/Special:FilePath/Composed%20salad.jpg', true),
('Normal Fruit Cocktail', 'ኖርማል ኮክቴል', null, 460, 'Salads', 'https://commons.wikimedia.org/wiki/Special:FilePath/Fruit%20bowl%20with%20fruits.png', true),
('Special Fruit Cocktail', 'ስፔሻል ኮክቴል', null, 670, 'Salads', 'https://commons.wikimedia.org/wiki/Special:FilePath/Fruit%20bowl%20with%20fruits.png', true),
('Tuna Salad', 'አትክልት በቱና', null, 520, 'Salads', 'https://commons.wikimedia.org/wiki/Special:FilePath/Composed%20salad.jpg', true),
('Special Mix', 'ስፔሻል', null, 635, 'Salads', 'https://commons.wikimedia.org/wiki/Special:FilePath/Composed%20salad.jpg', true),
('Pasta/Rice with Vegetables', 'ፓስታ/ሩዝ በአትክልት', null, 290, 'Pasta', 'https://commons.wikimedia.org/wiki/Special:FilePath/Pasta.jpg', true),
('Pasta/Rice with Salad', 'ፓስታ/ሩዝ በሰላጣ', null, 290, 'Pasta', 'https://commons.wikimedia.org/wiki/Special:FilePath/Pasta.jpg', true),
('Pasta/Rice with Meat', 'ፓስታ/ሩዝ በሥጋ', null, 460, 'Pasta', 'https://commons.wikimedia.org/wiki/Special:FilePath/Pasta.jpg', true),
('Pasta/Rice with Tuna', 'ፓስታ/ሩዝ በቱና', null, 520, 'Pasta', 'https://commons.wikimedia.org/wiki/Special:FilePath/Pasta.jpg', true),
('Pasta/Rice with Egg', 'ፓስታ/ሩዝ በእንቁላል', null, 450, 'Pasta', 'https://commons.wikimedia.org/wiki/Special:FilePath/Pasta.jpg', true),
('Special Pasta/Rice', 'ስፔሻል ፓስታ/ሩዝ', null, 575, 'Pasta', 'https://commons.wikimedia.org/wiki/Special:FilePath/Pasta.jpg', true),
('Shiro Feses (Loose Shiro)', 'ሽሮ ፈሰስ', null, 230, 'Shiro & Traditional', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ethiopian%20Shiro%20(11354785095).jpg', true),
('Shiro Tegabino', 'ሽሮ ተጋቢኖ', null, 290, 'Shiro & Traditional', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ethiopian%20Shiro%20(11354785095).jpg', true),
('Bozena Shiro (with Meat)', 'ቦዘና ሽሮ', null, 400, 'Shiro & Traditional', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ethiopian%20Shiro%20(11354785095).jpg', true),
('Siga Tibs (Beef Tibs)', 'ሥጋ ጥብስ', null, 575, 'Shiro & Traditional', 'https://commons.wikimedia.org/wiki/Special:FilePath/Siga%20Tibs.jpg', true),
('Tea', 'ሻይ', null, 40, 'Hot Drinks', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mug%20of%20Tea%20(10155541664).jpg', true),
('Coffee', 'ቡና', null, 60, 'Hot Drinks', 'https://commons.wikimedia.org/wiki/Special:FilePath/A%20small%20cup%20of%20coffee.JPG', true),
('Macchiato', 'ማኪያቶ', null, 80, 'Hot Drinks', 'https://commons.wikimedia.org/wiki/Special:FilePath/Latte%20macchiato.jpg', true),
('Spris (Tea & Coffee Mix)', 'ስፕሪስ', null, 60, 'Hot Drinks', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mug%20of%20Tea%20(10155541664).jpg', true),
('Keser (Herbal Tea)', 'ቀስር', null, 60, 'Hot Drinks', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mug%20of%20Tea%20(10155541664).jpg', true),
('Ice Tea', 'አይስ ሻይ', null, 50, 'Hot Drinks', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mug%20of%20Tea%20(10155541664).jpg', true);