insert into public.menu_items (name_en, name_am, description, price, category, image_url, available) values
('Tuna Sandwich', 'ቱና ሳንድዊች', null, 520, 'Sandwiches', 'https://commons.wikimedia.org/wiki/Special:FilePath/Club-sandwich.jpg', true),
('Egg Sandwich', 'እንቁላል ሳንድዊች', null, 345, 'Sandwiches', 'https://commons.wikimedia.org/wiki/Special:FilePath/Club-sandwich.jpg', true),
('Club Sandwich', 'ክለብ ሳንድዊች', null, 520, 'Sandwiches', 'https://commons.wikimedia.org/wiki/Special:FilePath/Club-sandwich.jpg', true),
('Vegetable Sandwich', 'አትክልት ሳንድዊች', null, 345, 'Sandwiches', 'https://commons.wikimedia.org/wiki/Special:FilePath/Club-sandwich.jpg', true),
('Z Special Club Sandwich', 'Z ስፔሻል ክለብ ሳንድዊች', null, 575, 'Sandwiches', 'https://commons.wikimedia.org/wiki/Special:FilePath/Club-sandwich.jpg', true),
('Quanta Firfir (Dried Beef Firfir)', 'ቁንጣ ፍርፍር', null, 460, 'Firfir', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kitcha%20fit%20fit.png', true),
('Tibs Firfir (Sauteed Meat Firfir)', 'ጥብስ ፍርፍር', null, 575, 'Firfir', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kitcha%20fit%20fit.png', true),
('Special Flex / Cornflakes Firfir', 'ስፔሻል የፍሌክስ ፍርፍር', null, 575, 'Firfir', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kitcha%20fit%20fit.png', true),
('Normal Firfir', 'ኖርማል ፍርፍር', null, 230, 'Firfir', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kitcha%20fit%20fit.png', true),
('Ful with Avocado', 'ፉል በአቮካዶ', null, 230, 'Ful', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ful%20medames%20(arabic%20meal).jpg', true),
('Normal Ful', 'ኖርማል ፉል', null, 175, 'Ful', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ful%20medames%20(arabic%20meal).jpg', true),
('Special Ful', 'ስፔሻል ፉል', null, 345, 'Ful', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ful%20medames%20(arabic%20meal).jpg', true),
('Ful with Egg', 'ፉል በእንቁላል', null, 300, 'Ful', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ful%20medames%20(arabic%20meal).jpg', true),
('Egg with Meat', 'እንቁላል በስጋ', null, 400, 'Egg Dishes', 'https://commons.wikimedia.org/wiki/Special:FilePath/Egg%20omelette.JPG', true),
('Scrambled Egg Sils', 'እንቁላል ስልስ', null, 300, 'Egg Dishes', 'https://commons.wikimedia.org/wiki/Special:FilePath/Scrambled%20eggs.png', true),
('Egg Omelette', 'እንቁላል አምሌት', null, 300, 'Egg Dishes', 'https://commons.wikimedia.org/wiki/Special:FilePath/Omelette.JPG', true),
('Egg with Tuna', 'እንቁላል በቱና', null, 460, 'Egg Dishes', 'https://commons.wikimedia.org/wiki/Special:FilePath/Egg%20omelette.JPG', true),
('Egg Firfir', 'እንቁላል ፍርፍር', null, 300, 'Egg Dishes', 'https://commons.wikimedia.org/wiki/Special:FilePath/Scrambled%20eggs.png', true),
('Egg with Avocado', 'እንቁላል በአቮካዶ', null, 325, 'Egg Dishes', 'https://commons.wikimedia.org/wiki/Special:FilePath/Egg%20omelette.JPG', true),
('Chechebsa', 'ጨጨብሳ', null, 230, 'Traditional Breakfast', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kitcha%20fit%20fit.png', true),
('Melawa', 'መላዋ', null, 175, 'Traditional Breakfast', 'https://commons.wikimedia.org/wiki/Special:FilePath/Injera%20from%20ivory%20teff.jpg', true),
('Fetira', 'ፈጡራ', null, 300, 'Traditional Breakfast', 'https://commons.wikimedia.org/wiki/Special:FilePath/Injera%20from%20ivory%20teff.jpg', true),
('Z Special Fetira', 'Z ስፔሻል ፈጡራ', null, 460, 'Traditional Breakfast', 'https://commons.wikimedia.org/wiki/Special:FilePath/Injera%20from%20ivory%20teff.jpg', true),
('Z Special Chechebsa', 'Z ስፔሻል ጨጨብሳ', null, 345, 'Traditional Breakfast', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kitcha%20fit%20fit.png', true),
('Pancake with Chocolate', 'ፓንኬክ በቸኮሌት', null, 230, 'Desserts', 'https://commons.wikimedia.org/wiki/Special:FilePath/Chocolate%20pancake.jpg', true);