insert into public.menu_items (name_en, name_am, description, price, category, image_url, available) values
('Strawberry Mojito', 'ሞጂቶ ስትሮቤሪ', null, 325, 'Mojito', 'https://commons.wikimedia.org/wiki/Special:FilePath/Strawberry%20Mojito%20(Unsplash).jpg', true),
('Pineapple Mojito', 'ሞጂቶ አናናስ', null, 299, 'Mojito', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mojito.jpg', true),
('Watermelon Mojito', 'ሀብሀብ ሞጂቶ', null, 300, 'Mojito', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mojito.jpg', true),
('Lemon Mojito', 'ሞጂቶ ሌሞን', null, 299, 'Mojito', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mojito.jpg', true),
('Orange Mojito', 'ሞጂቶ ብርቱካን', null, 310, 'Mojito', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mojito.jpg', true),
('Watermelon Juice', 'ሀብሀብ ጁስ', null, 230, 'Juice', 'https://commons.wikimedia.org/wiki/Special:FilePath/Watermelon%20juice%20in%20a%20glass.jpg', true),
('Strawberry Juice', 'ስትሮቤሪ', null, 325, 'Juice', 'https://commons.wikimedia.org/wiki/Special:FilePath/Watermelon%20juice%20in%20a%20glass.jpg', true),
('Mango Juice', 'ማንጎ', null, 325, 'Juice', 'https://commons.wikimedia.org/wiki/Special:FilePath/Glass%20of%20Mango%20Juice.jpg', true),
('Avocado Juice', 'አቮካዶ', null, 265, 'Juice', 'https://commons.wikimedia.org/wiki/Special:FilePath/Watermelon%20juice%20in%20a%20glass.jpg', true),
('Papaya Juice', 'ፓፓያ', null, 230, 'Juice', 'https://commons.wikimedia.org/wiki/Special:FilePath/Watermelon%20juice%20in%20a%20glass.jpg', true),
('Pineapple Juice', 'አናናስ ጁስ', null, 265, 'Juice', 'https://commons.wikimedia.org/wiki/Special:FilePath/Watermelon%20juice%20in%20a%20glass.jpg', true),
('Spris Juice / Mixed', 'ስፕሪስ ጁስ', null, 325, 'Juice', 'https://commons.wikimedia.org/wiki/Special:FilePath/Watermelon%20juice%20in%20a%20glass.jpg', true),
('Takaba Juice', 'ተካባ ጁስ', null, 230, 'Juice', 'https://commons.wikimedia.org/wiki/Special:FilePath/Watermelon%20juice%20in%20a%20glass.jpg', true),
('Orange Juice', 'ብርቱካን ጁስ', null, 300, 'Juice', 'https://commons.wikimedia.org/wiki/Special:FilePath/Watermelon%20juice%20in%20a%20glass.jpg', true),
('Lemon Juice', 'ሎሚ ጁስ', null, 265, 'Juice', 'https://commons.wikimedia.org/wiki/Special:FilePath/Watermelon%20juice%20in%20a%20glass.jpg', true),
('Z Special Juice', 'Z ስፔሻል ጁስ', null, 380, 'Juice', 'https://commons.wikimedia.org/wiki/Special:FilePath/Watermelon%20juice%20in%20a%20glass.jpg', true),
('Avocado Milkshake', 'አቮካዶ ሚልካሼክ', null, 325, 'Milkshake', 'https://commons.wikimedia.org/wiki/Special:FilePath/Chocolate%20milkshake.JPG', true),
('Strawberry Milkshake', 'ስትሮቤሪ ሚልካሼክ', null, 345, 'Milkshake', 'https://commons.wikimedia.org/wiki/Special:FilePath/Strawberry%20milk%20shake%20(cropped).jpg', true),
('Mango Milkshake', 'ማንጎ ሚልካሼክ', null, 345, 'Milkshake', 'https://commons.wikimedia.org/wiki/Special:FilePath/Chocolate%20milkshake.JPG', true),
('Banana Milkshake', 'ሙዝ ሚልካሼክ', null, 310, 'Milkshake', 'https://commons.wikimedia.org/wiki/Special:FilePath/Chocolate%20milkshake.JPG', true),
('Oreo Cream Shake', 'ኦሮ ክሬም ጁስ / ኦሪዮ ክሬም', null, 400, 'Milkshake', 'https://commons.wikimedia.org/wiki/Special:FilePath/Chocolate%20milkshake.JPG', true),
('Chocolate Cream Shake', 'ቸኮሌት ክሬም ጁስ', null, 400, 'Milkshake', 'https://commons.wikimedia.org/wiki/Special:FilePath/Chocolate%20milkshake.JPG', true);